CREATE TABLE `guestbook_entries` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `message` text NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO guestbook_entries (name, email, message, created_at, updated_at) VALUES
('Jane Doe', 'jane@example.com', 'Glad to be here.', NOW(), NULL),
('Alice Johnson', 'alice.johnson@example.com', 'Great experience!', NOW(), NULL),
('Bob Smith', 'bob.smith@example.com', 'Love this platform.', NOW(), NULL),
('Carol White', 'carol.white@example.com', 'Amazing service!', NOW(), NULL),
('David Brown', 'david.brown@example.com', 'Highly recommend.', NOW(), NULL),
('Emma Davis', 'emma.davis@example.com', 'Very impressed.', NOW(), NULL),
('Frank Miller', 'frank.miller@example.com', 'Excellent work!', NOW(), NULL),
('Grace Wilson', 'grace.wilson@example.com', 'Top notch!', NOW(), NULL),
('Henry Moore', 'henry.moore@example.com', 'Really satisfied.', NOW(), NULL),
('Ivy Taylor', 'ivy.taylor@example.com', 'Best in class.', NOW(), NULL),
('Jack Anderson', 'jack.anderson@example.com', 'Fantastic!', NOW(), NULL),
('Kate Thomas', 'kate.thomas@example.com', 'Wonderful experience.', NOW(), NULL),
('Leo Jackson', 'leo.jackson@example.com', 'Brilliant service.', NOW(), NULL),
('Mia Martin', 'mia.martin@example.com', 'Outstanding!', NOW(), NULL),
('Noah Lee', 'noah.lee@example.com', 'Perfect experience.', NOW(), NULL),
('Olivia Harris', 'olivia.harris@example.com', 'Very professional.', NOW(), NULL),
('Peter Clark', 'peter.clark@example.com', 'Impressed!', NOW(), NULL),
('Quinn Lewis', 'quinn.lewis@example.com', 'Great job!', NOW(), NULL),
('Rachel Walker', 'rachel.walker@example.com', 'Superb!', NOW(), NULL),
('Sam Hall', 'sam.hall@example.com', 'Excellent quality.', NOW(), NULL),
('Tina Allen', 'tina.allen@example.com', 'Best service.', NOW(), NULL),
('Umar Young', 'umar.young@example.com', 'Really good.', NOW(), NULL),
('Vanessa King', 'vanessa.king@example.com', 'Love it!', NOW(), NULL),
('William Wright', 'william.wright@example.com', 'Amazing!', NOW(), NULL),
('Xena Lopez', 'xena.lopez@example.com', 'Fantastic experience.', NOW(), NULL),
('Yuri Hill', 'yuri.hill@example.com', 'Very satisfied.', NOW(), NULL),
('Zoe Scott', 'zoe.scott@example.com', 'Perfect!', NOW(), NULL),
('Aaron Green', 'aaron.green@example.com', 'Awesome service.', NOW(), NULL),
('Bella Adams', 'bella.adams@example.com', 'Great stuff!', NOW(), NULL),
('Chris Nelson', 'chris.nelson@example.com', 'Very good.', NOW(), NULL),
('Diana Carter', 'diana.carter@example.com', 'Excellent!', NOW(), NULL),
('Ethan Mitchell', 'ethan.mitchell@example.com', 'Outstanding!', NOW(), NULL),
('Fiona Perez', 'fiona.perez@example.com', 'Wonderful!', NOW(), NULL),
('George Roberts', 'george.roberts@example.com', 'Top quality.', NOW(), NULL),
('Hannah Phillips', 'hannah.phillips@example.com', 'Really impressed.', NOW(), NULL),
('Isaac Campbell', 'isaac.campbell@example.com', 'Superb quality.', NOW(), NULL),
('Jasmine Parker', 'jasmine.parker@example.com', 'Best experience.', NOW(), NULL),
('Kevin Evans', 'kevin.evans@example.com', 'Highly satisfied.', NOW(), NULL),
('Luna Edwards', 'luna.edwards@example.com', 'Fantastic service.', NOW(), NULL),
('Marcus Collins', 'marcus.collins@example.com', 'Great platform.', NOW(), NULL),
('Natalie Stewart', 'natalie.stewart@example.com', 'Excellent choice.', NOW(), NULL),
('Oscar Sanchez', 'oscar.sanchez@example.com', 'Very professional.', NOW(), NULL),
('Piper Morris', 'piper.morris@example.com', 'Wonderful service.', NOW(), NULL),
('Quinn Rogers', 'quinn.rogers@example.com', 'Awesome!', NOW(), NULL),
('Riley Rogers', 'riley.rogers@example.com', 'Best choice.', NOW(), NULL),
('Sophie Reed', 'sophie.reed@example.com', 'Highly recommend.', NOW(), NULL),
('Thomas Cook', 'thomas.cook@example.com', 'Perfect quality.', NOW(), NULL),
('Uma Morgan', 'uma.morgan@example.com', 'Excellent work.', NOW(), NULL),
('Victor Bell', 'victor.bell@example.com', 'Outstanding service.', NOW(), NULL),
('Wendy Murphy', 'wendy.murphy@example.com', 'Great experience.', NOW(), NULL),
('Xavier Bailey', 'xavier.bailey@example.com', 'Superb!', NOW(), NULL),
('Yara Rivera', 'yara.rivera@example.com', 'Very good.', NOW(), NULL),
('Zara Cooper', 'zara.cooper@example.com', 'Love this!', NOW(), NULL),
('Adrian Richardson', 'adrian.richardson@example.com', 'Fantastic!', NOW(), NULL),
('Bella Cox', 'bella.cox@example.com', 'Excellent service.', NOW(), NULL),
('Caleb Howard', 'caleb.howard@example.com', 'Great job!', NOW(), NULL),
('Daisy Ward', 'daisy.ward@example.com', 'Wonderful!', NOW(), NULL),
('Evan Torres', 'evan.torres@example.com', 'Perfect!', NOW(), NULL),
('Freya Peterson', 'freya.peterson@example.com', 'Best service.', NOW(), NULL),
('Gabriel Gray', 'gabriel.gray@example.com', 'Highly satisfied.', NOW(), NULL),
('Hazel Ramirez', 'hazel.ramirez@example.com', 'Outstanding!', NOW(), NULL),
('Ian James', 'ian.james@example.com', 'Excellent choice.', NOW(), NULL),
('Jade Watson', 'jade.watson@example.com', 'Great platform.', NOW(), NULL),
('Kai Brooks', 'kai.brooks@example.com', 'Very impressed.', NOW(), NULL),
('Lily Chavez', 'lily.chavez@example.com', 'Fantastic experience.', NOW(), NULL),
('Marcus Bennet', 'marcus.bennet@example.com', 'Awesome service.', NOW(), NULL),
('Nina Palmer', 'nina.palmer@example.com', 'Perfect quality.', NOW(), NULL),
('Oscar Barnett', 'oscar.barnett@example.com', 'Superb!', NOW(), NULL),
('Piper Kelley', 'piper.kelley@example.com', 'Wonderful experience.', NOW(), NULL),
('Quincy Crowe', 'quincy.crowe@example.com', 'Best experience.', NOW(), NULL),
('Ruby Silva', 'ruby.silva@example.com', 'Highly recommend.', NOW(), NULL),
('Simon Pearson', 'simon.pearson@example.com', 'Great work!', NOW(), NULL),
('Tessa Nichols', 'tessa.nichols@example.com', 'Excellent!', NOW(), NULL),
('Ulysses Salazar', 'ulysses.salazar@example.com', 'Outstanding quality.', NOW(), NULL),
('Violet Casey', 'violet.casey@example.com', 'Very good service.', NOW(), NULL),
('Walter Cain', 'walter.cain@example.com', 'Fantastic!', NOW(), NULL),
('Willow Frost', 'willow.frost@example.com', 'Love the service!', NOW(), NULL),
('Xavier Newman', 'xavier.newman@example.com', 'Perfect service.', NOW(), NULL),
('Yvonne Byrd', 'yvonne.byrd@example.com', 'Highly satisfied.', NOW(), NULL),
('Zachary Shelton', 'zachary.shelton@example.com', 'Excellent platform.', NOW(), NULL),
('Amber Hodges', 'amber.hodges@example.com', 'Great experience.', NOW(), NULL),
('Bryce Mccarthy', 'bryce.mccarthy@example.com', 'Wonderful service.', NOW(), NULL),
('Chloe Hale', 'chloe.hale@example.com', 'Outstanding!', NOW(), NULL),
('Dominic Pike', 'dominic.pike@example.com', 'Best quality.', NOW(), NULL),
('Eloise Potts', 'eloise.potts@example.com', 'Highly impressed.', NOW(), NULL);